name: Release
on:
  push:
    branches: [ master, next ]

jobs:
  release:
    name: Node.js
    uses: cnpm/github-actions/.github/workflows/node-release.yml@master
    secrets:
      NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
      GIT_TOKEN: ${{ secrets.GIT_TOKEN }}
